# -*- mode: ruby -*-
# vi: set ft=ruby  :

#########################################################################################################
#													#
# 	This Vagrantfile make an hybrid lab on virtualbox with Linux, Mac and Windows Machines		#
#													#
# 	Default Configuration requires 13GB of free RAM							#
# 	4GB of RAM its the minimal for Windows and MacOSx 						#
# 	Increase or decrease RAM configuration for any machine if necessary				#
#	Dont forget to create the entries on hosts files 						#
#		Linux   -> /etc/hosts 									#
#		Windows -> C:\Windows\system32\drivers\etc\hosts					#
#													#
#		10.11.11.10	server.caiodelgado.example						#
#		10.11.11.11	database.caiodelgado.example						#
#		10.11.11.20	ubuntu.caiodelgado.example						#
#		10.11.11.21	centos.caiodelgado.example						#
#		10.11.11.30	windows.caiodelgado.example						#
#		10.11.11.40	macosx.caiodelgado.example						#
#													#
#########################################################################################################


machines = {
  "ubuntu20"   => {"memory" => "2048", "cpu" => "2", "ip" => "10", "image" => "bento/ubuntu-20.04"},
  "worker1"   => {"memory" => "1024", "cpu" => "1", "ip" => "20", "image" => "ubuntu/bionic64"},
  "worker2"   => {"memory" => "1024", "cpu" => "1", "ip" => "30", "image" => "ubuntu/bionic64"}
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.network "private_network", ip: "10.10.11.#{conf["ip"]}"
      machine.vm.provision "shell", path: "./provision.sh"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/swarm-lab"]
      end

      # if "#{name}" == "macosx" 
      #   machine.vm.synced_folder ".", "/vagrant",
      #     id: "core",
      #     :nfs => true,
      #     :mount_options => ['nolock,vers=3,udp,noatime,actimeo=1,resvport'],
      #     :export_options => ['async,insecure,no_subtree_check,no_acl,no_root_squash']
      # end

    end
  end
end
